src/home/urls.py
from django.urls import path
from . import views


app_name = 'home'


urlpatterns = [
    path('', views.home , name='home'),
]

src/project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('property/', include('property.urls' , namespace='property') ),
    path('agents/', include('agents.urls' , namespace='agents') ),
    path('about/', include('about.urls' , namespace='about') ),
    path('contact/', include('contact.urls' , namespace='contact') ),
    path('', include('home.urls' , namespace='home') )
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




admin.site.site_header = "AGENCY RESERVATION ADMINISTRATION"
admin.site.site_title = "AGENCY RESERVATION ADMINISTRATION"
admin.site.site_index_title = "Welcome To Agency Reservation Administration"

src/property/urls.py
from django.urls import path
from . import views


app_name = 'property'

urlpatterns = [
    path('', views.property_list , name='property_list'),
    path('<slug:category_slug>' , views.property_list , name='property_list_category') ,
    path('detail/<slug:property_slug>', views.property_detail , name='property_detail'),
]

src/property/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify


import random
from django.conf import settings
import os
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
# Create your models here.

property_type = (
    ('Sale', "sale"),
    ('Rent', "rent")
)

price_category = (
    ('1000 --> 5000 QAR','1000 --> 5000 QAR'),
    ('5000 --> 10000 QAR','5000 --> 10000 QAR'),
    ('10000 --> 15000 QAR','10000 --> 15000 QAR'),
    ('15000 --> 20000 QAR','15000 --> 20000 QAR'),
    ('20000 --> 30000 QAR','20000 --> 30000 QAR'),
    ('30000 --> 50000 QAR','30000 --> 50000 QAR'),
    ('50000 --> 75000 QAR','50000 --> 75000 QAR'),
    ('75000 --> 100000 QAR','75000 --> 100000 QAR'),
    ('100000 --> 125000 QAR','100000 --> 125000 QAR'),
    ('125000 --> 150000 QAR','125000 --> 150000 QAR'),
    ('150000 --> 200000 QAR','150000 --> 200000 QAR'),
    ('200000 --> 1000000 QAR','200000 --> 1000000 QAR'),
    )

STOREY = (
    ('Bungalow', 'Bungalow'),
    ('Duplex', 'Duplex'),
    ('One Storeys', 'One Storeys'),
    ('Two Storeys', 'Two Storeys'),
    ('Three Storeys', 'Three Storeys'),
    ('Four Storeys', 'Four Storeys'),
    ('Five Storeys', 'Five Storeys'),
)



FURNISHED = (
    ('Full Furnished', 'Full Furnished'),
    ('Semi Furnished', 'Semi Furnished'),
    ('None Furnished', 'None Furnished'),
)

NEW_PROPERTY = (
    ('yes', 'yes'),
    ('no', 'no'),
)

PARKING_SPACE = (
    ('yes', 'yes'),
    ('no', 'no'),
)

BEDROOM = (
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
    ('6', '6'),
)

DURATION = (
    ('1 month', '1 month'),
    ('3 months', '3 months'),
    ('6 months', '6 months'),
    ('Year', 'Year'),
    ('2 Years', '2 Years'),
    ('3 Years', '3 Years'),

)

BATHROOM = (
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
    ('6', '6'),
)
PURPOSE = (
    ('Residential', 'Residential'),
    ('Commercial', 'Commercial'),
)


class Property(models.Model):
    name = models.CharField(max_length=50)
    desc = models.TextField()
    adress = models.CharField( max_length=80)
    type = models.CharField(choices=property_type, max_length=50)
    storey = models.CharField(choices=STOREY, max_length=50)
    furnished = models.CharField(choices=FURNISHED, max_length=50)
    parking_space = models.CharField(choices=PARKING_SPACE, max_length=50)
    new_property = models.CharField(choices=NEW_PROPERTY, max_length=50)
    purpose = models.CharField(choices=PURPOSE, max_length=50)
    duration = models.CharField(choices=DURATION, max_length=50)
    category = models.ForeignKey("Category",null=True , on_delete=models.SET_NULL)
    neighborhood = models.ForeignKey("Neighborhood",default ="2", null=True , on_delete=models.SET_NULL)
    price = models.PositiveIntegerField()
    pricecat = models.CharField(choices=price_category, max_length=50)
    area = models.DecimalField( max_digits=5, decimal_places=2)
    rooms_number = models.PositiveIntegerField()
    beds_number = models.PositiveIntegerField()
    baths_number = models.PositiveIntegerField()
    garages_number = models.PositiveIntegerField()
    image = models.ImageField(upload_to='property/', height_field=None, width_field=None, max_length=None)
    created = models.DateTimeField(default=timezone.now)

    slug = models.SlugField(blank=True  , null=True)

    def save(self , *args , **kwargs):
        if not self.slug and self.name :
            self.slug = slugify(self.name)
        super(Property , self).save(*args , **kwargs)

    class Meta:
        verbose_name = ("Property")
        verbose_name_plural = ("properties")

    def __str__(self):
        return self.name

class PropertyImages(models.Model):
    property = models.ForeignKey(Property , on_delete=models.CASCADE)
    image = models.ImageField(upload_to='propertyimg/' , blank=True , null=True)

    def __str__(self):
        return self.property.name

    class Meta:
        verbose_name = 'Property Image'
        verbose_name_plural = 'Property Images'



class Category(models.Model):
    category_name = models.CharField(max_length=50)
    category_image = models.ImageField(upload_to='category/', height_field=None, width_field=None, max_length=None)

    slug = models.SlugField(blank=True  , null=True)


    def save(self , *args , **kwargs):
        if not self.slug and self.category_name :
            self.slug = slugify(self.category_name)
        super(Category , self).save(*args , **kwargs)


    class Meta:
        verbose_name = ("category")
        verbose_name_plural = ("categories")

    def __str__(self):
        return self.category_name


class Neighborhood(models.Model):
    title        = models.CharField(max_length=120, blank=True, unique=True)
    image        = models.ImageField(upload_to='neighborhoods/', null=True, blank=True)
    slug         = models.SlugField(blank=True,unique=True , null=True)
    category     = models.ForeignKey(Category,blank=True, default=1, max_length=300, unique=False, on_delete=models.CASCADE)


    def save(self , *args , **kwargs):
        if not self.slug and self.title :
            self.slug = slugify(self.title)
        super(Neighborhood , self).save(*args , **kwargs)

    def __str__(self):
        return self.slug




class Reserve(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=254)
    notes = models.TextField()

    class Meta:
        verbose_name = ("Reserve")
        verbose_name_plural = ("Reservations")

    def __str__(self):
        return self.name

src/property/forms.py
from django import forms
from .models import Reserve , Property , PropertyImages
from django.core.validators import validate_image_file_extension
from django.utils.translation import gettext as _


class ReserveForm(forms.ModelForm):

    class Meta:
        model = Reserve
        fields = "__all__"





class ShowAdminForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = (
            "name",
            "slug",
        )

    photos = forms.FileField(
        widget=forms.ClearableFileInput(attrs={"multiple": True}),
        label=_("Add photos"),
        required=False,
    )

    def clean_photos(self):
        """Make sure only images can be uploaded."""
        for upload in self.files.getlist("photos"):
            validate_image_file_extension(upload)

    def save_photos(self, show):
        """Process each uploaded image."""
        for upload in self.files.getlist("photos"):
            photo = PropertyImages(show=show, photo=upload)
            photo.save()

src/property/views.py
from django.shortcuts import render

# Create your views here.
from .models import Property , Category , PropertyImages
from .forms import ReserveForm
from django.core.paginator import Paginator
from django.db.models import Count
from django.db.models import Q
from django.shortcuts import get_object_or_404


def property_list(request , category_slug=None):
    category = None
    property_list = Property.objects.all()
    category_list = Category.objects.annotate(total_properties=Count('property'))

    if category_slug :
        category = get_object_or_404(Category ,slug=category_slug)
        property_list = property_list.filter(category=category)


    adress_query = request.GET.get('q')
    property_type = request.GET.getlist('property_type' , None)
    furnished = request.GET.getlist('furnished' , None)
    purpose = request.GET.getlist('purpose' , None)
    price_cat = request.GET.getlist('price_category', None)

    if adress_query and property_type and furnished and purpose and price_cat :
        property_list = property_list.filter(
            Q(adress__icontains = adress_query) &
            Q(type__icontains = property_type[0]) &
            Q(furnished__icontains = furnished[0]) &
            Q(purpose__icontains = purpose[0]) &
            Q(pricecat__icontains = price_cat[0])
        ).distinct()




    paginator = Paginator(property_list, 3) # Show 25 contacts per page
    page = request.GET.get('page')
    property_list = paginator.get_page(page)
    template = 'property/list.html'





    context = {
        'property_list' : property_list ,
        'category_list' : category_list ,
        'category' : category
    }

    return render(request, template , context)




def property_detail(request, property_slug):
    property_detail = Property.objects.get(slug=property_slug)
    property_images = PropertyImages.objects.filter(property=property_detail)
    template = 'property/detail.html'


    if request.method == 'POST':
        reserve_form = ReserveForm(request.POST)
        if reserve_form.is_valid():
            reserve_form.save()


    else:
        reserve_form = ReserveForm()


    context = {
        'property_detail' : property_detail ,
        'reserve_form' : reserve_form ,
        'property_images' : property_images
    }

    return render(request, template, context)

src/property/templates/property/detail.html
 {% extends 'base.html' %}
 {% load static %}
 {% load bootstrap4 %}
 {% block body %}
  <!-- END: header -->


  <section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

            <div class="page-title probootstrap-animate">
              <div class="probootstrap-breadcrumbs">
                <a href="#">Home</a><span><a href="{% url 'property:property_list' %}"> Properties </a></span>
              </div>
              <h1>{{property_detail}}</h1>
            </div>

          </div>
        </div>
      </div>
    </div>
    <ul class="slides">

      <li style="background-image: url({% static 'img/slider_1.jpg' %}); background-size: 100% 100%;" ></li>
      <li style="background-image: url({% static 'img/slider_2.jpg' %}); background-size: 100% 100%;" ></li>
      <li style="background-image: url({% static 'img/slider_3.jpg' %}); background-size: 100% 100%;" ></li>
    </ul>
  </section>
  <!-- END: slider  -->


  <section class="probootstrap-section">
    <div class="container">
      <div class="row">
        <div class="col-md-10">
					<div class="flexslider">
						<ul class="slides">

                            {% for image in property_images %}

                                <li>
                                    <img src="{{image.image.url}}" class="img-responsive" />
                                </li>

                            {% endfor %}
						</ul>
					</div>
					<!-- FlexSlider -->
					  <script defer src="{% static 'js/scripts.js' %}"></script>
					  <script defer src="{% static 'js/jquery.flexslider.js' %}"></script>
					<link rel="stylesheet" href="{% static 'css/flexslider.css' %}" type="text/css" media="screen" />

						<script>
					// Can also be used with $(document).ready()
					$(window).load(function() {
					  $('.flexslider').flexslider({
						animation: "slide",
						controlNav: "thumbnails"
					  });
					});
					</script>
					<!-- //FlexSlider -->
      </div>
      <div style="
  margin: 10px;
  padding: 20px;
  font-size: 15px;">
        <div class="col-md-6">
          <h2>Description</h2>
          <p><strong>{{property_detail.category}}</strong></p>
          <p>{{property_detail.desc}}</p>
          <p>For {{property_detail.type}}</p>
          <p>{{property_detail.adress}}</p>
          <p>{{property_detail.price}} $</p>
        </div>
        <div class="col-md-6">
          <br>
          <br>
          <br>
          <br>
          <br>
          <p>Area: {{property_detail.area}}m²</p>
          <p>Rooms: {{property_detail.rooms_number}}</p>
          <p>Beds: {{property_detail.beds_number}}</p>
          <p>Baths: {{property_detail.baths_number}}</p>
          <p>Garages: {{property_detail.garages_number}}</p>
        </div>
      </div>
    </div>
  </section>

    <section class="probootstrap-section">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2>Reserve This Property</h2>
            <form action="" method="POST">
              {% csrf_token %}
              {% bootstrap_form reserve_form %}
              {% buttons %}
                  <button type="submit" class="btn btn-primary">Reserve</button>
              {% endbuttons %}
            </form>
        </div>
      </div>
    </div>
  </section>





  {% endblock body %}

src/property/templates/property/list.html
 {% extends 'base.html' %}
 {% load static %}
 {% block body %}

  <!-- END: header -->
  <section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

            <div class="page-title probootstrap-animate">
              <div class="probootstrap-breadcrumbs">
                <a href="/">Home</a><span>Properties</span>
              </div>
              <h1>Properties</h1>
              <h3> Select your category </h3>
				<ul>


					{% for category in category_list %}

					<li style="display: inline-block; "><a style="color: #fff;" href="{% url 'property:property_list_category' category.slug  %}" > {{category.category_name}} <span class="num-of-ads">({{category.total_properties}})</span></a></li>

					{% endfor %}
				</ul>
            </div>

          </div>
        </div>
      </div>
    </div>
    <ul class="slides">
      <li style="background-image: url({% static 'img/slider_1.jpg' %}); background-size: 100% 100%;" ></li>
      <li style="background-image: url({% static 'img/slider_2.jpg' %}); background-size: 100% 100%;" ></li>
      <li style="background-image: url({% static 'img/slider_3.jpg' %}); background-size: 100% 100%;" ></li>
    </ul>
  </section>
  <!-- END: slider  -->

  <section class="probootstrap-section probootstrap-section-lighter">
    <div class="container">
      <div class="row">

        {% if property_list %}

          {% for property in property_list %}
            <div class="col-md-4 col-sm-6">
              <div class="probootstrap-card probootstrap-listing">
                <div class="probootstrap-card-media">
                  <img src="{{property.image.url}}" class="img-responsive" alt="">
                  <a href="#" class="probootstrap-love"><i class="icon-heart"></i></a>
                </div>
                <div class="probootstrap-card-text">
                  <h2 class="probootstrap-card-heading"><a href="{% url 'property:property_detail' property.slug %}">{{property.name}}</a></h2>
                  <div class="probootstrap-listing-location">
                    <i class="icon-location2"></i> <span>{{property.adress}}</span>
                  </div>
                  <div class="probootstrap-listing-category for-sale"><span>for {{property.type}}</span></div>
                  <div class="probootstrap-listing-price"><strong>{{property.price}}</strong> QAR / month</div>
                </div>
                <div class="probootstrap-card-extra">
                  <ul>
                    <li>
                      Area
                      <span>{{property.area}} m2</span>
                    </li>
                    <li>
                      Rooms
                      <span>{{property.rooms_number}}</span>
                    </li>
                    <li>
                      Beds
                      <span>{{property.beds_number}}</span>
                    </li>
                    <li>
                      Baths
                      <span>{{property.baths_number}}</span>
                    </li>
                  </ul>
                </div>
              </div>
              <!-- END listing -->
            </div>
          {% endfor %}

        {% else %}

            <div class="col-md-10 col-sm-10">
              <h2>No Property with this Adress or Type</h2>
            </div>

        {% endif %}
      </div>
    </div>
  </section>

   {% if property_list.has_other_pages %}

                            <ul class="pagination pagination-sm">
                                {% if property_list.has_previous %}
                                    <li><a href="?page={{ property_list.previous_page_number }}">Prev</a></li>
                                {% else %}
                                    <li class="disabled"></li>
                                {% endif %}

                                {% for pages in property_list.paginator.page_range %}
                                    {% if property_list.number == pages %}
                                        <li><a href="#">{{pages}}</a></li>
                                    {% else %}
                                        <li><a href="?page={{pages}}">{{pages}}</a></li>
                                    {% endif %}

                                {% endfor %}


                                {% if property_list.has_next %}
                                    <li><a href="?page={{ property_list.next_page_number }}">Next</a></li>
                                {% else %}
                                    <li class="disabled"></li>
                                {% endif %}

                            </ul>

                        {% endif %}



   {% endblock body %}